#!/bin/bash

# Dirs
dirs=(
  "app/api/v1/endpoints"
  "app/api/v1/schemas"
  "app/application/commands"
  "app/application/queries"
  "app/core"
  "app/domain/interfaces"
  "app/domain"
  "app/infrastructure/db/repositories"
  "app/infrastructure/outbox"
  "app/infrastructure/cache"
  "app/infrastructure/messaging"
  "app/grpc_client/proto"
  "app/grpc_client/generated"
  "app/workers"
  "migrations/versions"
  "tests/fakes"
  "tests/api"
  "tests/unit/domain"
  "tests/unit/application"
  "tests/unit/infrastructure"
)

for d in "${dirs[@]}"; do
  mkdir -p "$d"
done

# Files
files=(
  "app/__init__.py"
  "app/main.py"

  "app/api/__init__.py"
  "app/api/v1/__init__.py"
  "app/api/v1/routers.py"
  "app/api/v1/endpoints/__init__.py"
  "app/api/v1/endpoints/portfolios.py"
  "app/api/v1/endpoints/transactions.py"
  "app/api/v1/endpoints/analytics.py"
  "app/api/v1/endpoints/alerts.py"
  "app/api/v1/endpoints/watchlists.py"
  "app/api/v1/schemas/__init__.py"
  "app/api/v1/schemas/portfolios.py"
  "app/api/v1/schemas/transactions.py"
  "app/api/v1/schemas/analytics.py"
  "app/api/v1/schemas/alerts.py"
  "app/api/v1/schemas/watchlists.py"
  "app/api/v1/schemas/errors.py"

  "app/application/__init__.py"
  "app/application/dto.py"
  "app/application/commands/__init__.py"
  "app/application/commands/create_portfolio.py"
  "app/application/commands/delete_portfolio.py"
  "app/application/commands/add_transaction.py"
  "app/application/commands/set_price_alert.py"
  "app/application/commands/delete_price_alert.py"
  "app/application/commands/add_to_watchlist.py"
  "app/application/commands/remove_from_watchlist.py"
  "app/application/queries/__init__.py"
  "app/application/queries/get_portfolio.py"
  "app/application/queries/get_portfolio_analytics.py"
  "app/application/queries/get_transactions.py"
  "app/application/queries/get_watchlist.py"

  "app/core/__init__.py"
  "app/core/config.py"
  "app/core/dependencies.py"

  "app/domain/__init__.py"
  "app/domain/entities.py"
  "app/domain/value_objects.py"
  "app/domain/events.py"
  "app/domain/exceptions.py"
  "app/domain/interfaces/__init__.py"
  "app/domain/interfaces/i_portfolio_repo.py"
  "app/domain/interfaces/i_position_repo.py"
  "app/domain/interfaces/i_transaction_repo.py"
  "app/domain/interfaces/i_alert_repo.py"

  "app/infrastructure/__init__.py"
  "app/infrastructure/db/__init__.py"
  "app/infrastructure/db/models.py"
  "app/infrastructure/db/session.py"
  "app/infrastructure/db/unit_of_work.py"
  "app/infrastructure/db/repositories/__init__.py"
  "app/infrastructure/db/repositories/portfolio_repo.py"
  "app/infrastructure/db/repositories/position_repo.py"
  "app/infrastructure/db/repositories/transaction_repo.py"
  "app/infrastructure/db/repositories/alert_repo.py"
  "app/infrastructure/outbox/__init__.py"
  "app/infrastructure/outbox/models.py"
  "app/infrastructure/outbox/outbox_repo.py"
  "app/infrastructure/cache/__init__.py"
  "app/infrastructure/cache/redis_client.py"
  "app/infrastructure/cache/pnl_cache.py"
  "app/infrastructure/messaging/__init__.py"
  "app/infrastructure/messaging/publisher.py"
  "app/infrastructure/messaging/consumer.py"
  "app/infrastructure/messaging/schemas.py"

  "app/grpc_client/__init__.py"
  "app/grpc_client/market_client.py"
  "app/grpc_client/proto/__init__.py"
  "app/grpc_client/proto/market.proto"
  "app/grpc_client/generated/__init__.py"
  "app/grpc_client/generated/market_pb2.py"
  "app/grpc_client/generated/market_pb2_grpc.py"

  "app/workers/__init__.py"
  "app/workers/celery_app.py"
  "app/workers/outbox_relay.py"
  "app/workers/alert_checker.py"

  "migrations/env.py"
  "migrations/script.py.mako"
  "migrations/versions/0001_init.py"
  "migrations/versions/0002_add_version_to_portfolio.py"
  "migrations/versions/0003_add_outbox_events.py"

  "tests/__init__.py"
  "tests/conftest.py"
  "tests/fakes/__init__.py"
  "tests/fakes/fake_portfolio_repo.py"
  "tests/fakes/fake_position_repo.py"
  "tests/fakes/fake_transaction_repo.py"
  "tests/fakes/fake_alert_repo.py"
  "tests/fakes/fake_market_client.py"
  "tests/fakes/fake_pnl_cache.py"
  "tests/api/__init__.py"
  "tests/api/conftest.py"
  "tests/api/test_portfolios.py"
  "tests/api/test_transactions.py"
  "tests/api/test_analytics.py"
  "tests/api/test_alerts.py"
  "tests/api/test_watchlists.py"
  "tests/unit/__init__.py"
  "tests/unit/domain/__init__.py"
  "tests/unit/domain/test_entities.py"
  "tests/unit/domain/test_value_objects.py"
  "tests/unit/domain/test_events.py"
  "tests/unit/application/__init__.py"
  "tests/unit/application/test_add_transaction.py"
  "tests/unit/application/test_create_portfolio.py"
  "tests/unit/application/test_get_analytics.py"
  "tests/unit/application/test_set_price_alert.py"
  "tests/unit/infrastructure/__init__.py"
  "tests/unit/infrastructure/test_unit_of_work.py"
  "tests/unit/infrastructure/test_outbox_relay.py"
  "tests/unit/infrastructure/test_consumer.py"
  "tests/unit/infrastructure/test_pnl_cache.py"
)

for f in "${files[@]}"; do
  touch "$f"
done

echo "Done"
